[wokwi]
version = 1
elf = ".pio/build/esp32pio : O termo 'pio' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável. Verifique a grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente novamente./firmware.elf"
firmware = ".pio/build/esp32/firmware.bin"